services:
  web:
    image: ivanovka87/softuni:web
    deploy:
      replicas: 5
    ports:
      - 8080:8080
    volumes:
      - "/home/vagrant/SoftUni/web/src:/var/www/html:ro"
    networks:
      - app
  db:
    image: ivanovka87/softuni:db
    networks:
      - app
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
secrets:
  db_root_password:
    external: true      
networks:
  app: